In [ ]:
import numpy as np
import math

M = 40
K = 40
N = 40

TILE = 8

In [ ]:
np.random.seed(42)

A = np.random.randint(-15, 16, size=(M, K))
B = np.random.randint(-15, 16, size=(K, N))
print("A =", A)
print("B =", B)

A = [[ -9   4  13 ...   1  11  11]
 [ 15  -6  12 ...  -9  -4  13]
 [ -8  -1 -13 ...   0  -3   2]
 ...
 [-11  11  -6 ...  -6  -8 -10]
 [-10  -8   7 ...  13  -2  -8]
 [ -7   6  -5 ...  -5 -10 -14]]
B = [[ -9   2  11 ...   6  12  15]
 [ 13  -8   1 ... -12 -15  -8]
 [ 13   7  -9 ...  -8 -14 -13]
 ...
 [ -7   1  -5 ...   5  -8 -10]
 [ -8   2 -13 ...   9   7   0]
 [ -4   1   0 ...  13  -2 -12]]


In [ ]:

C = A @ B
print ("C = ", C)
print("A shape =", A.shape)
print("B shape =", B.shape)
print("C shape =", C.shape)


C =  [[ 406 -578 -293 ...  252 -485 -381]
 [-328 -353 -400 ...  154  143  664]
 [ -78  -60   67 ...  203  284 -318]
 ...
 [-429  234 -136 ... -592  312 -358]
 [-109  811  999 ...  329 -490 -234]
 [-144 -455 1107 ...   40   48 -397]]
A shape = (40, 40)
B shape = (40, 40)
C shape = (40, 40)


In [ ]:

np.savetxt("A.csv", A, fmt="%d", delimiter=",")
np.savetxt("B.csv", B, fmt="%d", delimiter=",")
np.savetxt("golden.csv", C, fmt="%d", delimiter=",")

In [ ]:
#cycle model
m_tiles = math.ceil(M / TILE)
k_tiles = math.ceil(K / TILE)
n_tiles = math.ceil(N / TILE)
tile_mults = m_tiles * k_tiles * n_tiles

cycles_per_tile = 36
#CHOOSE   1
#LOAD     1
#COMPUTE 24
#DRAIN    9
#DONE     1
#---------
#36 cycles

predicted_cycles = tile_mults * cycles_per_tile

In [ ]:

total_macs = M * K * N

macs_per_cycle = total_macs / predicted_cycles

peak_macs_per_cycle = TILE * TILE

utilization = 100 * macs_per_cycle / peak_macs_per_cycle

In [ ]:
print("\n------SYSTOLIC ARRAY REPORT--------")

print(f"Matrix Size      : {M} x {K} * {K} x {N}")
print(f"Tile Size        : {TILE} x {TILE}")

print(f"\nM Tiles          : {m_tiles}")
print(f"K Tiles          : {k_tiles}")
print(f"N Tiles          : {n_tiles}")

print(f"\nTile Multiplies  : {tile_mults}")

print(f"Cycles/Tile      : {cycles_per_tile}")
print(f"Predicted Cycles : {predicted_cycles}")

print(f"\nTotal MACs       : {total_macs}")

print(f"MACs/Cycle       : {macs_per_cycle:.2f}")

print(f"Peak MACs/Cycle  : {peak_macs_per_cycle}")

print(f"Utilization      : {utilization:.2f}%")


------SYSTOLIC ARRAY REPORT--------
Matrix Size      : 40 x 40 * 40 x 40
Tile Size        : 8 x 8

M Tiles          : 5
K Tiles          : 5
N Tiles          : 5

Tile Multiplies  : 125
Cycles/Tile      : 36
Predicted Cycles : 4500

Total MACs       : 64000
MACs/Cycle       : 14.22
Peak MACs/Cycle  : 64
Utilization      : 22.22%
